name: Build and Release

on:
  push:
    tags:
      - "v*" # e.g., v1.0.0

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
        run: |
          mkdir -p bin/${{ matrix.goos }}
          EXT=""
          [ "${{ matrix.goos }}" = "windows" ] && EXT=".exe"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o bin/${{ matrix.goos }}/ntptest${EXT} main.go

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ntptest-${{ matrix.goos }}
          path: bin/${{ matrix.goos }}/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
